export const ID_REGIONS = [
  { name: 'Jakarta Pusat',    province: 'DKI Jakarta',      type: 'city' },
  { name: 'Jakarta Selatan',  province: 'DKI Jakarta',      type: 'city' },
  { name: 'Jakarta Barat',    province: 'DKI Jakarta',      type: 'city' },
  { name: 'Jakarta Utara',    province: 'DKI Jakarta',      type: 'city' },
  { name: 'Jakarta Timur',    province: 'DKI Jakarta',      type: 'city' },
  { name: 'DKI Jakarta',      province: '',                  type: 'province' },
  { name: 'Bandung',          province: 'Jawa Barat',       type: 'city' },
  { name: 'Bekasi',           province: 'Jawa Barat',       type: 'city' },
  { name: 'Depok',            province: 'Jawa Barat',       type: 'city' },
  { name: 'Bogor',            province: 'Jawa Barat',       type: 'city' },
  { name: 'Cimahi',           province: 'Jawa Barat',       type: 'city' },
  { name: 'Cirebon',          province: 'Jawa Barat',       type: 'city' },
  { name: 'Tasikmalaya',      province: 'Jawa Barat',       type: 'city' },
  { name: 'Sukabumi',         province: 'Jawa Barat',       type: 'city' },
  { name: 'Karawang',         province: 'Jawa Barat',       type: 'city' },
  { name: 'Jawa Barat',       province: '',                  type: 'province' },
  { name: 'Tangerang',        province: 'Banten',           type: 'city' },
  { name: 'Tangerang Selatan', province: 'Banten',          type: 'city' },
  { name: 'Serang',           province: 'Banten',           type: 'city' },
  { name: 'Cilegon',          province: 'Banten',           type: 'city' },
  { name: 'Banten',           province: '',                  type: 'province' },
  { name: 'Semarang',         province: 'Jawa Tengah',      type: 'city' },
  { name: 'Solo',             province: 'Jawa Tengah',      type: 'city' },
  { name: 'Surakarta',        province: 'Jawa Tengah',      type: 'city' },
  { name: 'Magelang',         province: 'Jawa Tengah',      type: 'city' },
  { name: 'Tegal',            province: 'Jawa Tengah',      type: 'city' },
  { name: 'Pekalongan',       province: 'Jawa Tengah',      type: 'city' },
  { name: 'Salatiga',         province: 'Jawa Tengah',      type: 'city' },
  { name: 'Purwokerto',       province: 'Jawa Tengah',      type: 'city' },
  { name: 'Jawa Tengah',      province: '',                  type: 'province' },
  { name: 'Yogyakarta',       province: 'DI Yogyakarta',    type: 'city' },
  { name: 'Sleman',           province: 'DI Yogyakarta',    type: 'city' },
  { name: 'Bantul',           province: 'DI Yogyakarta',    type: 'city' },
  { name: 'DI Yogyakarta',    province: '',                  type: 'province' },
  { name: 'Surabaya',         province: 'Jawa Timur',       type: 'city' },
  { name: 'Malang',           province: 'Jawa Timur',       type: 'city' },
  { name: 'Sidoarjo',         province: 'Jawa Timur',       type: 'city' },
  { name: 'Gresik',           province: 'Jawa Timur',       type: 'city' },
  { name: 'Mojokerto',        province: 'Jawa Timur',       type: 'city' },
  { name: 'Kediri',           province: 'Jawa Timur',       type: 'city' },
  { name: 'Blitar',           province: 'Jawa Timur',       type: 'city' },
  { name: 'Pasuruan',         province: 'Jawa Timur',       type: 'city' },
  { name: 'Probolinggo',      province: 'Jawa Timur',       type: 'city' },
  { name: 'Batu',             province: 'Jawa Timur',       type: 'city' },
  { name: 'Jawa Timur',       province: '',                  type: 'province' },
  { name: 'Medan',            province: 'Sumatera Utara',   type: 'city' },
  { name: 'Binjai',           province: 'Sumatera Utara',   type: 'city' },
  { name: 'Pematangsiantar',  province: 'Sumatera Utara',   type: 'city' },
  { name: 'Sumatera Utara',   province: '',                  type: 'province' },
  { name: 'Padang',           province: 'Sumatera Barat',   type: 'city' },
  { name: 'Bukittinggi',      province: 'Sumatera Barat',   type: 'city' },
  { name: 'Sumatera Barat',   province: '',                  type: 'province' },
  { name: 'Pekanbaru',        province: 'Riau',             type: 'city' },
  { name: 'Dumai',            province: 'Riau',             type: 'city' },
  { name: 'Riau',             province: '',                  type: 'province' },
  { name: 'Batam',            province: 'Kep. Riau',        type: 'city' },
  { name: 'Tanjungpinang',    province: 'Kep. Riau',        type: 'city' },
  { name: 'Kep. Riau',        province: '',                  type: 'province' },
  { name: 'Palembang',        province: 'Sumatera Selatan', type: 'city' },
  { name: 'Lubuklinggau',     province: 'Sumatera Selatan', type: 'city' },
  { name: 'Sumatera Selatan', province: '',                  type: 'province' },
  { name: 'Bandar Lampung',   province: 'Lampung',          type: 'city' },
  { name: 'Metro',            province: 'Lampung',          type: 'city' },
  { name: 'Lampung',          province: '',                  type: 'province' },
  { name: 'Denpasar',         province: 'Bali',             type: 'city' },
  { name: 'Badung',           province: 'Bali',             type: 'city' },
  { name: 'Gianyar',          province: 'Bali',             type: 'city' },
  { name: 'Bali',             province: '',                  type: 'province' },
  { name: 'Makassar',         province: 'Sulawesi Selatan', type: 'city' },
  { name: 'Parepare',         province: 'Sulawesi Selatan', type: 'city' },
  { name: 'Palopo',           province: 'Sulawesi Selatan', type: 'city' },
  { name: 'Sulawesi Selatan', province: '',                  type: 'province' },
  { name: 'Samarinda',        province: 'Kalimantan Timur', type: 'city' },
  { name: 'Balikpapan',       province: 'Kalimantan Timur', type: 'city' },
  { name: 'Bontang',          province: 'Kalimantan Timur', type: 'city' },
  { name: 'Kalimantan Timur', province: '',                  type: 'province' },
  { name: 'Banjarmasin',      province: 'Kalimantan Selatan', type: 'city' },
  { name: 'Banjarbaru',       province: 'Kalimantan Selatan', type: 'city' },
  { name: 'Kalimantan Selatan', province: '',                type: 'province' },
  { name: 'Pontianak',        province: 'Kalimantan Barat', type: 'city' },
  { name: 'Singkawang',       province: 'Kalimantan Barat', type: 'city' },
  { name: 'Kalimantan Barat', province: '',                  type: 'province' },
  { name: 'Palangka Raya',    province: 'Kalimantan Tengah', type: 'city' },
  { name: 'Kalimantan Tengah', province: '',                 type: 'province' },
  { name: 'Tarakan',          province: 'Kalimantan Utara', type: 'city' },
  { name: 'Kalimantan Utara', province: '',                  type: 'province' },
  { name: 'Manado',           province: 'Sulawesi Utara',   type: 'city' },
  { name: 'Bitung',           province: 'Sulawesi Utara',   type: 'city' },
  { name: 'Sulawesi Utara',   province: '',                  type: 'province' },
  { name: 'Palu',             province: 'Sulawesi Tengah',  type: 'city' },
  { name: 'Sulawesi Tengah',  province: '',                  type: 'province' },
  { name: 'Kendari',          province: 'Sulawesi Tenggara', type: 'city' },
  { name: 'Sulawesi Tenggara', province: '',                 type: 'province' },
  { name: 'Banda Aceh',       province: 'Aceh',             type: 'city' },
  { name: 'Lhokseumawe',      province: 'Aceh',             type: 'city' },
  { name: 'Aceh',             province: '',                  type: 'province' },
  { name: 'Jayapura',         province: 'Papua',            type: 'city' },
  { name: 'Papua',            province: '',                  type: 'province' },
  { name: 'Manokwari',        province: 'Papua Barat',      type: 'city' },
  { name: 'Sorong',           province: 'Papua Barat',      type: 'city' },
  { name: 'Papua Barat',      province: '',                  type: 'province' },
  { name: 'Ambon',            province: 'Maluku',           type: 'city' },
  { name: 'Maluku',           province: '',                  type: 'province' },
  { name: 'Ternate',          province: 'Maluku Utara',     type: 'city' },
  { name: 'Maluku Utara',     province: '',                  type: 'province' },
  { name: 'Mataram',          province: 'NTB',              type: 'city' },
  { name: 'NTB',              province: '',                  type: 'province' },
  { name: 'Nusa Tenggara Barat', province: '',              type: 'province' },
  { name: 'Kupang',           province: 'NTT',              type: 'city' },
  { name: 'NTT',              province: '',                  type: 'province' },
  { name: 'Nusa Tenggara Timur', province: '',              type: 'province' },
  { name: 'Jambi',            province: 'Jambi',            type: 'city' },
  { name: 'Jambi',            province: '',                  type: 'province' },
  { name: 'Bengkulu',         province: 'Bengkulu',         type: 'city' },
  { name: 'Bengkulu',         province: '',                  type: 'province' },
  { name: 'Pangkalpinang',    province: 'Kep. Bangka Belitung', type: 'city' },
  { name: 'Kep. Bangka Belitung', province: '',             type: 'province' },
  { name: 'Gorontalo',        province: 'Gorontalo',        type: 'city' },
  { name: 'Gorontalo',        province: '',                  type: 'province' },
  { name: 'Mamuju',           province: 'Sulawesi Barat',   type: 'city' },
  { name: 'Sulawesi Barat',   province: '',                  type: 'province' },
];
